version: '3.8'

volumes:
  postgres-data:
    driver: local
  bundle_cache:
    driver: local
services:
  postgres:
    image: postgres:11.7-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: ''
    volumes:
      - .:/app:cached
      - postgres-data:/var/lib/postgresql/data:cached
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - bundle_cache:/bundle:cached
      - .:/app
    depends_on:
      - postgres
    command: tail -f /dev/null